stages:
  prepare:
    cmd: python prepare.py
    deps:
    - data/raw.csv
    outs:
    - data/prepared.csv

  train:
    cmd: python train.py
    deps: 
      - data/prepared.csv
    outs:
      - models/tree.pkl
